[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /vault-log/logs/teleport-auth/*.log
    Tag               teleport.auth
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/teleport-proxy-a/*.log
    Tag               teleport.proxy-a
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/teleport-proxy-b/*.log
    Tag               teleport.proxy-b
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/audit/events/*.log
    Tag               teleport.audit
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/nodes/lab-linux-01/*.log,/vault-log/logs/nodes/lab-linux-01/teleport/*.log
    Tag               node.lab-linux-01
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/nodes/lab-linux-02/*.log,/vault-log/logs/nodes/lab-linux-02/teleport/*.log
    Tag               node.lab-linux-02
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/nodes/lab-linux-03/*.log,/vault-log/logs/nodes/lab-linux-03/teleport/*.log
    Tag               node.lab-linux-03
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/nodes/lab-admin-01/*.log,/vault-log/logs/nodes/lab-admin-01/teleport/*.log
    Tag               node.lab-admin-01
    Refresh_Interval  5
    Read_from_Head    true

[INPUT]
    Name              tail
    Path              /vault-log/logs/nodes/vault-log/*.log,/vault-log/logs/nodes/vault-log/teleport/*.log
    Tag               node.vault-log
    Refresh_Interval  5
    Read_from_Head    true

[FILTER]
    Name              record_modifier
    Match             teleport.auth
    Record            hostname teleport-auth
    Record            app teleport-auth

[FILTER]
    Name              record_modifier
    Match             teleport.proxy-a
    Record            hostname teleport-proxy-a
    Record            app teleport-proxy-a

[FILTER]
    Name              record_modifier
    Match             teleport.proxy-b
    Record            hostname teleport-proxy-b
    Record            app teleport-proxy-b

[FILTER]
    Name              record_modifier
    Match             teleport.audit
    Record            hostname teleport-auth
    Record            app teleport-audit

[FILTER]
    Name              record_modifier
    Match             node.lab-linux-01
    Record            hostname lab-linux-01
    Record            app lab-node

[FILTER]
    Name              record_modifier
    Match             node.lab-linux-02
    Record            hostname lab-linux-02
    Record            app lab-node

[FILTER]
    Name              record_modifier
    Match             node.lab-linux-03
    Record            hostname lab-linux-03
    Record            app lab-node

[FILTER]
    Name              record_modifier
    Match             node.lab-admin-01
    Record            hostname lab-admin-01
    Record            app lab-node

[FILTER]
    Name              record_modifier
    Match             node.vault-log
    Record            hostname vault-log
    Record            app lab-node

[OUTPUT]
    Name                syslog
    Match               *
    Host                vault-log-rsyslog
    Port                514
    Mode                tcp
    Syslog_Format       rfc5424
    Syslog_Hostname_Key hostname
    Syslog_Appname_Key  app
    Syslog_Message_Key  log
